// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.FortuneTeller
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("fortune")]
        public string Fortune { get; set; }

        [JsonProperty("insight")]
        public string Insight { get; set; }

        [JsonProperty("timeframe")]
        public string Timeframe { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("question")]
        public object Question { get; set; }

        [JsonProperty("luckyNumbers")]
        public long[] LuckyNumbers { get; set; }

        [JsonProperty("luckyElement")]
        public string LuckyElement { get; set; }

        [JsonProperty("luckyColor")]
        public string LuckyColor { get; set; }

        [JsonProperty("luckyDay")]
        public string LuckyDay { get; set; }

        [JsonProperty("timestamp")]
        public DateTimeOffset Timestamp { get; set; }
    }
}
